// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/export/export.proto

package exportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"` // "pdf" | "csv"
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Records       []*Record              `protobuf:"bytes,3,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_proto_export_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_proto_export_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ExportRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_export_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_export_export_proto_rawDescGZIP(), []int{1}
}

func (x *Record) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_proto_export_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_proto_export_export_proto_rawDescGZIP(), []int{2}
}

func (x *ExportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_export_export_proto protoreflect.FileDescriptor

const file_proto_export_export_proto_rawDesc = "" +
	"\n" +
	"\x19proto/export/export.proto\x12\x06export\"n\n" +
	"\rExportRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12(\n" +
	"\arecords\x18\x03 \x03(\v2\x0e.export.RecordR\arecords\"w\n" +
	"\x06Record\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.export.Record.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x0eExportResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType2\xd2\x01\n" +
	"\rExportService\x12>\n" +
	"\rExportCharges\x12\x15.export.ExportRequest\x1a\x16.export.ExportResponse\x12>\n" +
	"\rExportTickets\x12\x15.export.ExportRequest\x1a\x16.export.ExportResponse\x12A\n" +
	"\x10ExportDeliveries\x12\x15.export.ExportRequest\x1a\x16.export.ExportResponseB>Z<github.com/dianaglobal/painel-autor-go/proto/export;exportpbb\x06proto3"

var (
	file_proto_export_export_proto_rawDescOnce sync.Once
	file_proto_export_export_proto_rawDescData []byte
)

func file_proto_export_export_proto_rawDescGZIP() []byte {
	file_proto_export_export_proto_rawDescOnce.Do(func() {
		file_proto_export_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_export_export_proto_rawDesc), len(file_proto_export_export_proto_rawDesc)))
	})
	return file_proto_export_export_proto_rawDescData
}

var file_proto_export_export_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_export_export_proto_goTypes = []any{
	(*ExportRequest)(nil),  // 0: export.ExportRequest
	(*Record)(nil),         // 1: export.Record
	(*ExportResponse)(nil), // 2: export.ExportResponse
	nil,                    // 3: export.Record.FieldsEntry
}
var file_proto_export_export_proto_depIdxs = []int32{
	1, // 0: export.ExportRequest.records:type_name -> export.Record
	3, // 1: export.Record.fields:type_name -> export.Record.FieldsEntry
	0, // 2: export.ExportService.ExportCharges:input_type -> export.ExportRequest
	0, // 3: export.ExportService.ExportTickets:input_type -> export.ExportRequest
	0, // 4: export.ExportService.ExportDeliveries:input_type -> export.ExportRequest
	2, // 5: export.ExportService.ExportCharges:output_type -> export.ExportResponse
	2, // 6: export.ExportService.ExportTickets:output_type -> export.ExportResponse
	2, // 7: export.ExportService.ExportDeliveries:output_type -> export.ExportResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_export_export_proto_init() }
func file_proto_export_export_proto_init() {
	if File_proto_export_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_export_export_proto_rawDesc), len(file_proto_export_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_export_export_proto_goTypes,
		DependencyIndexes: file_proto_export_export_proto_depIdxs,
		MessageInfos:      file_proto_export_export_proto_msgTypes,
	}.Build()
	File_proto_export_export_proto = out.File
	file_proto_export_export_proto_goTypes = nil
	file_proto_export_export_proto_depIdxs = nil
}
